### ISSUE TITLE
Old repo

### ISSUE THREAD

**Issue by mutageneral** [corbindavenport/cobalt#8]
Are you able to archive this old repo of cobalt or change the readme to let people know this version exist?
https://github.com/Cobalt-OS/Cobalt
I think websites like ArchiveOS links to the old one, so it would be cool for the people to know this is still getting updated.

**Comment by corbindavenport** [comment]
Yeah I still have write access, I'll add a note to the readme. I was waiting until nightly builds were available, and I just switched those on today 😄

**Comment by corbindavenport** [comment]
Done.
